// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoveYourBody.Service;

namespace MoveYourBody.Service.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MoveYourBody.Service.Models.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Training_session_id")
                        .HasColumnType("int");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("MoveYourBody.Service.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Img_src")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Img_src = "box.jpg",
                            Name = "Box"
                        },
                        new
                        {
                            Id = 2,
                            Img_src = "crossFitt.jpg",
                            Name = "Crossfit"
                        },
                        new
                        {
                            Id = 3,
                            Img_src = "football.jpg",
                            Name = "Labdarúgás"
                        },
                        new
                        {
                            Id = 4,
                            Img_src = "basketball.jpg",
                            Name = "Kosárlabda"
                        },
                        new
                        {
                            Id = 5,
                            Img_src = "handball.jpg",
                            Name = "Kézilabda"
                        },
                        new
                        {
                            Id = 6,
                            Img_src = "volleyball.jpg",
                            Name = "Röplabda"
                        },
                        new
                        {
                            Id = 7,
                            Img_src = "spartan.jpg",
                            Name = "Spartan"
                        },
                        new
                        {
                            Id = 8,
                            Img_src = "tennis.jpg",
                            Name = "Tenisz"
                        },
                        new
                        {
                            Id = 9,
                            Img_src = "trx.jpg",
                            Name = "TRX"
                        },
                        new
                        {
                            Id = 10,
                            Img_src = "swimming.jpg",
                            Name = "Úszás"
                        },
                        new
                        {
                            Id = 11,
                            Img_src = "riding.jpg",
                            Name = "Lovaglás"
                        },
                        new
                        {
                            Id = 12,
                            Img_src = "yoga.jpg",
                            Name = "Jóga"
                        });
                });

            modelBuilder.Entity("MoveYourBody.Service.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City_name")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("County_name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City_name = "Aba",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 2,
                            City_name = "Abádszalók",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 3,
                            City_name = "Abaújszántó",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 4,
                            City_name = "Abony",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 5,
                            City_name = "Ács",
                            County_name = "Komárom-Esztergom"
                        },
                        new
                        {
                            Id = 6,
                            City_name = "Adony",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 7,
                            City_name = "Ajak",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 8,
                            City_name = "Ajka",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 9,
                            City_name = "Albertirsa",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 10,
                            City_name = "Alsózsolca",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 11,
                            City_name = "Aszód",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 12,
                            City_name = "Bábolna",
                            County_name = "Komárom-Esztergom"
                        },
                        new
                        {
                            Id = 13,
                            City_name = "Bácsalmás",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 14,
                            City_name = "Badacsonytomaj",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 15,
                            City_name = "Baja",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 16,
                            City_name = "Baktalórántháza",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 17,
                            City_name = "Balassagyarmat",
                            County_name = "Nógrád"
                        },
                        new
                        {
                            Id = 18,
                            City_name = "Balatonalmádi",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 19,
                            City_name = "Balatonboglár",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 20,
                            City_name = "Balatonföldvár",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 21,
                            City_name = "Balatonfüred",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 22,
                            City_name = "Balatonfűzfő",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 23,
                            City_name = "Balatonkenese",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 24,
                            City_name = "Balatonlelle",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 25,
                            City_name = "Balkány",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 26,
                            City_name = "Balmazújváros",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 27,
                            City_name = "Barcs",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 28,
                            City_name = "Bátaszék",
                            County_name = "Tolna"
                        },
                        new
                        {
                            Id = 29,
                            City_name = "Bátonyterenye",
                            County_name = "Nógrád"
                        },
                        new
                        {
                            Id = 30,
                            City_name = "Battonya",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 31,
                            City_name = "Békés",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 32,
                            City_name = "Békéscsaba",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 33,
                            City_name = "Bélapátfalva",
                            County_name = "Heves"
                        },
                        new
                        {
                            Id = 34,
                            City_name = "Beled",
                            County_name = "Győr-Moson-Sopron"
                        },
                        new
                        {
                            Id = 35,
                            City_name = "Berettyóújfalu",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 36,
                            City_name = "Berhida",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 37,
                            City_name = "Besenyszög",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 38,
                            City_name = "Biatorbágy",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 39,
                            City_name = "Bicske",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 40,
                            City_name = "Biharkeresztes",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 41,
                            City_name = "Bodajk",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 42,
                            City_name = "Bóly",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 43,
                            City_name = "Bonyhád",
                            County_name = "Tolna"
                        },
                        new
                        {
                            Id = 44,
                            City_name = "Borsodnádasd",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 45,
                            City_name = "Budakalász",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 46,
                            City_name = "Budakeszi",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 47,
                            City_name = "Budaörs",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 48,
                            City_name = "Budapest",
                            County_name = "Budapest"
                        },
                        new
                        {
                            Id = 49,
                            City_name = "Bük",
                            County_name = "Vas"
                        },
                        new
                        {
                            Id = 50,
                            City_name = "Cegléd",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 51,
                            City_name = "Celldömölk",
                            County_name = "Vas"
                        },
                        new
                        {
                            Id = 52,
                            City_name = "Cigánd",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 53,
                            City_name = "Csákvár",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 54,
                            City_name = "Csanádpalota",
                            County_name = "Csongrád-Csanád"
                        },
                        new
                        {
                            Id = 55,
                            City_name = "Csenger",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 56,
                            City_name = "Csepreg",
                            County_name = "Vas"
                        },
                        new
                        {
                            Id = 57,
                            City_name = "Csongrád",
                            County_name = "Csongrád-Csanád"
                        },
                        new
                        {
                            Id = 58,
                            City_name = "Csorna",
                            County_name = "Győr-Moson-Sopron"
                        },
                        new
                        {
                            Id = 59,
                            City_name = "Csorvás",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 60,
                            City_name = "Csurgó",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 61,
                            City_name = "Dabas",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 62,
                            City_name = "Debrecen",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 63,
                            City_name = "Demecser",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 64,
                            City_name = "Derecske",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 65,
                            City_name = "Dévaványa",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 66,
                            City_name = "Devecser",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 67,
                            City_name = "Diósd",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 68,
                            City_name = "Dombóvár",
                            County_name = "Tolna"
                        },
                        new
                        {
                            Id = 69,
                            City_name = "Dombrád",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 70,
                            City_name = "Dorog",
                            County_name = "Komárom-Esztergom"
                        },
                        new
                        {
                            Id = 71,
                            City_name = "Dunaföldvár",
                            County_name = "Tolna"
                        },
                        new
                        {
                            Id = 72,
                            City_name = "Dunaharaszti",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 73,
                            City_name = "Dunakeszi",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 74,
                            City_name = "Dunaújváros",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 75,
                            City_name = "Dunavarsány",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 76,
                            City_name = "Dunavecse",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 77,
                            City_name = "Edelény",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 78,
                            City_name = "Eger",
                            County_name = "Heves"
                        },
                        new
                        {
                            Id = 79,
                            City_name = "Elek",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 80,
                            City_name = "Emőd",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 81,
                            City_name = "Encs",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 82,
                            City_name = "Enying",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 83,
                            City_name = "Ercsi",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 84,
                            City_name = "Érd",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 85,
                            City_name = "Esztergom",
                            County_name = "Komárom-Esztergom"
                        },
                        new
                        {
                            Id = 86,
                            City_name = "Fegyvernek",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 87,
                            City_name = "Fehérgyarmat",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 88,
                            City_name = "Felsőzsolca",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 89,
                            City_name = "Fertőd",
                            County_name = "Győr-Moson-Sopron"
                        },
                        new
                        {
                            Id = 90,
                            City_name = "Fertőszentmiklós",
                            County_name = "Győr-Moson-Sopron"
                        },
                        new
                        {
                            Id = 91,
                            City_name = "Fonyód",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 92,
                            City_name = "Fót",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 93,
                            City_name = "Füzesabony",
                            County_name = "Heves"
                        },
                        new
                        {
                            Id = 94,
                            City_name = "Füzesgyarmat",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 95,
                            City_name = "Gárdony",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 96,
                            City_name = "Göd",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 97,
                            City_name = "Gödöllő",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 98,
                            City_name = "Gönc",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 99,
                            City_name = "Gyál",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 100,
                            City_name = "Gyomaendrőd",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 101,
                            City_name = "Gyömrő",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 102,
                            City_name = "Gyöngyös",
                            County_name = "Heves"
                        },
                        new
                        {
                            Id = 103,
                            City_name = "Gyöngyöspata",
                            County_name = "Heves"
                        },
                        new
                        {
                            Id = 104,
                            City_name = "Gyönk",
                            County_name = "Tolna"
                        },
                        new
                        {
                            Id = 105,
                            City_name = "Győr",
                            County_name = "Győr-Moson-Sopron"
                        },
                        new
                        {
                            Id = 106,
                            City_name = "Gyula",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 107,
                            City_name = "Hajdúböszörmény",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 108,
                            City_name = "Hajdúdorog",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 109,
                            City_name = "Hajdúhadház",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 110,
                            City_name = "Hajdúnánás",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 111,
                            City_name = "Hajdúsámson",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 112,
                            City_name = "Hajdúszoboszló",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 113,
                            City_name = "Hajós",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 114,
                            City_name = "Halásztelek",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 115,
                            City_name = "Harkány",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 116,
                            City_name = "Hatvan",
                            County_name = "Heves"
                        },
                        new
                        {
                            Id = 117,
                            City_name = "Herend",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 118,
                            City_name = "Heves",
                            County_name = "Heves"
                        },
                        new
                        {
                            Id = 119,
                            City_name = "Hévíz",
                            County_name = "Zala"
                        },
                        new
                        {
                            Id = 120,
                            City_name = "Hódmezővásárhely",
                            County_name = "Csongrád-Csanád"
                        },
                        new
                        {
                            Id = 121,
                            City_name = "Ibrány",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 122,
                            City_name = "Igal",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 123,
                            City_name = "Isaszeg",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 124,
                            City_name = "Izsák",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 125,
                            City_name = "Jánoshalma",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 126,
                            City_name = "Jánosháza",
                            County_name = "Vas"
                        },
                        new
                        {
                            Id = 127,
                            City_name = "Jánossomorja",
                            County_name = "Győr-Moson-Sopron"
                        },
                        new
                        {
                            Id = 128,
                            City_name = "Jászapáti",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 129,
                            City_name = "Jászárokszállás",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 130,
                            City_name = "Jászberény",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 131,
                            City_name = "Jászfényszaru",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 132,
                            City_name = "Jászkisér",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 133,
                            City_name = "Kaba",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 134,
                            City_name = "Kadarkút",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 135,
                            City_name = "Kalocsa",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 136,
                            City_name = "Kaposvár",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 137,
                            City_name = "Kapuvár",
                            County_name = "Győr-Moson-Sopron"
                        },
                        new
                        {
                            Id = 138,
                            City_name = "Karcag",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 139,
                            City_name = "Kazincbarcika",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 140,
                            City_name = "Kecel",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 141,
                            City_name = "Kecskemét",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 142,
                            City_name = "Kemecse",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 143,
                            City_name = "Kenderes",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 144,
                            City_name = "Kerekegyháza",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 145,
                            City_name = "Kerepes",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 146,
                            City_name = "Keszthely",
                            County_name = "Zala"
                        },
                        new
                        {
                            Id = 147,
                            City_name = "Kisbér",
                            County_name = "Komárom-Esztergom"
                        },
                        new
                        {
                            Id = 148,
                            City_name = "Kisköre",
                            County_name = "Heves"
                        },
                        new
                        {
                            Id = 149,
                            City_name = "Kiskőrös",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 150,
                            City_name = "Kiskunfélegyháza",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 151,
                            City_name = "Kiskunhalas",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 152,
                            City_name = "Kiskunlacháza",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 153,
                            City_name = "Kiskunmajsa",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 154,
                            City_name = "Kistarcsa",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 155,
                            City_name = "Kistelek",
                            County_name = "Csongrád-Csanád"
                        },
                        new
                        {
                            Id = 156,
                            City_name = "Kisújszállás",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 157,
                            City_name = "Kisvárda",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 158,
                            City_name = "Komádi",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 159,
                            City_name = "Komárom",
                            County_name = "Komárom-Esztergom"
                        },
                        new
                        {
                            Id = 160,
                            City_name = "Komló",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 161,
                            City_name = "Kondoros",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 162,
                            City_name = "Kozármisleny",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 163,
                            City_name = "Körmend",
                            County_name = "Vas"
                        },
                        new
                        {
                            Id = 164,
                            City_name = "Körösladány",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 165,
                            City_name = "Kőszeg",
                            County_name = "Vas"
                        },
                        new
                        {
                            Id = 166,
                            City_name = "Kunhegyes",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 167,
                            City_name = "Kunszentmárton",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 168,
                            City_name = "Kunszentmiklós",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 169,
                            City_name = "Lábatlan",
                            County_name = "Komárom-Esztergom"
                        },
                        new
                        {
                            Id = 170,
                            City_name = "Lajosmizse",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 171,
                            City_name = "Lébény",
                            County_name = "Győr-Moson-Sopron"
                        },
                        new
                        {
                            Id = 172,
                            City_name = "Lengyeltóti",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 173,
                            City_name = "Lenti",
                            County_name = "Zala"
                        },
                        new
                        {
                            Id = 174,
                            City_name = "Létavértes",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 175,
                            City_name = "Letenye",
                            County_name = "Zala"
                        },
                        new
                        {
                            Id = 176,
                            City_name = "Lőrinci",
                            County_name = "Heves"
                        },
                        new
                        {
                            Id = 177,
                            City_name = "Maglód",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 178,
                            City_name = "Mágocs",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 179,
                            City_name = "Makó",
                            County_name = "Csongrád-Csanád"
                        },
                        new
                        {
                            Id = 180,
                            City_name = "Mándok",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 181,
                            City_name = "Marcali",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 182,
                            City_name = "Máriapócs",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 183,
                            City_name = "Martfű",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 184,
                            City_name = "Martonvásár",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 185,
                            City_name = "Mátészalka",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 186,
                            City_name = "Medgyesegyháza",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 187,
                            City_name = "Mélykút",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 188,
                            City_name = "Mezőberény",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 189,
                            City_name = "Mezőcsát",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 190,
                            City_name = "Mezőhegyes",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 191,
                            City_name = "Mezőkeresztes",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 192,
                            City_name = "Mezőkovácsháza",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 193,
                            City_name = "Mezőkövesd",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 194,
                            City_name = "Mezőtúr",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 195,
                            City_name = "Mindszent",
                            County_name = "Csongrád-Csanád"
                        },
                        new
                        {
                            Id = 196,
                            City_name = "Miskolc",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 197,
                            City_name = "Mohács",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 198,
                            City_name = "Monor",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 199,
                            City_name = "Mór",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 200,
                            City_name = "Mórahalom",
                            County_name = "Csongrád-Csanád"
                        },
                        new
                        {
                            Id = 201,
                            City_name = "Mosonmagyaróvár",
                            County_name = "Győr-Moson-Sopron"
                        },
                        new
                        {
                            Id = 202,
                            City_name = "Nádudvar",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 203,
                            City_name = "Nagyatád",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 204,
                            City_name = "Nagybajom",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 205,
                            City_name = "Nagyecsed",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 206,
                            City_name = "Nagyhalász",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 207,
                            City_name = "Nagykálló",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 208,
                            City_name = "Nagykanizsa",
                            County_name = "Zala"
                        },
                        new
                        {
                            Id = 209,
                            City_name = "Nagykáta",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 210,
                            City_name = "Nagykőrös",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 211,
                            City_name = "Nagymányok",
                            County_name = "Tolna"
                        },
                        new
                        {
                            Id = 212,
                            City_name = "Nagymaros",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 213,
                            City_name = "Nyékládháza",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 214,
                            City_name = "Nyergesújfalu",
                            County_name = "Komárom-Esztergom"
                        },
                        new
                        {
                            Id = 215,
                            City_name = "Nyíradony",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 216,
                            City_name = "Nyírbátor",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 217,
                            City_name = "Nyírbogát",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 218,
                            City_name = "Nyíregyháza",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 219,
                            City_name = "Nyírlugos",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 220,
                            City_name = "Nyírmada",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 221,
                            City_name = "Nyírtelek",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 222,
                            City_name = "Ócsa",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 223,
                            City_name = "Onga",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 224,
                            City_name = "Orosháza",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 225,
                            City_name = "Oroszlány",
                            County_name = "Komárom-Esztergom"
                        },
                        new
                        {
                            Id = 226,
                            City_name = "Ózd",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 227,
                            City_name = "Őrbottyán",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 228,
                            City_name = "Őriszentpéter",
                            County_name = "Vas"
                        },
                        new
                        {
                            Id = 229,
                            City_name = "Örkény",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 230,
                            City_name = "Pacsa",
                            County_name = "Zala"
                        },
                        new
                        {
                            Id = 231,
                            City_name = "Paks",
                            County_name = "Tolna"
                        },
                        new
                        {
                            Id = 232,
                            City_name = "Pálháza",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 233,
                            City_name = "Pannonhalma",
                            County_name = "Győr-Moson-Sopron"
                        },
                        new
                        {
                            Id = 234,
                            City_name = "Pápa",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 235,
                            City_name = "Pásztó",
                            County_name = "Nógrád"
                        },
                        new
                        {
                            Id = 236,
                            City_name = "Pécel",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 237,
                            City_name = "Pécs",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 238,
                            City_name = "Pécsvárad",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 239,
                            City_name = "Pétervására",
                            County_name = "Heves"
                        },
                        new
                        {
                            Id = 240,
                            City_name = "Pilis",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 241,
                            City_name = "Piliscsaba",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 242,
                            City_name = "Pilisvörösvár",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 243,
                            City_name = "Polgár",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 244,
                            City_name = "Polgárdi",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 245,
                            City_name = "Pomáz",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 246,
                            City_name = "Pusztaszabolcs",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 247,
                            City_name = "Putnok",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 248,
                            City_name = "Püspökladány",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 249,
                            City_name = "Rácalmás",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 250,
                            City_name = "Ráckeve",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 251,
                            City_name = "Rakamaz",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 252,
                            City_name = "Rákóczifalva",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 253,
                            City_name = "Répcelak",
                            County_name = "Vas"
                        },
                        new
                        {
                            Id = 254,
                            City_name = "Rétság",
                            County_name = "Nógrád"
                        },
                        new
                        {
                            Id = 255,
                            City_name = "Rudabánya",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 256,
                            City_name = "Sajóbábony",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 257,
                            City_name = "Sajószentpéter",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 258,
                            City_name = "Salgótarján",
                            County_name = "Nógrád"
                        },
                        new
                        {
                            Id = 259,
                            City_name = "Sándorfalva",
                            County_name = "Csongrád-Csanád"
                        },
                        new
                        {
                            Id = 260,
                            City_name = "Sárbogárd",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 261,
                            City_name = "Sarkad",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 262,
                            City_name = "Sárospatak",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 263,
                            City_name = "Sárvár",
                            County_name = "Vas"
                        },
                        new
                        {
                            Id = 264,
                            City_name = "Sásd",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 265,
                            City_name = "Sátoraljaújhely",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 266,
                            City_name = "Sellye",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 267,
                            City_name = "Siklós",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 268,
                            City_name = "Simontornya",
                            County_name = "Tolna"
                        },
                        new
                        {
                            Id = 269,
                            City_name = "Siófok",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 270,
                            City_name = "Solt",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 271,
                            City_name = "Soltvadkert",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 272,
                            City_name = "Sopron",
                            County_name = "Győr-Moson-Sopron"
                        },
                        new
                        {
                            Id = 273,
                            City_name = "Sülysáp",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 274,
                            City_name = "Sümeg",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 275,
                            City_name = "Szabadszállás",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 276,
                            City_name = "Szarvas",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 277,
                            City_name = "Százhalombatta",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 278,
                            City_name = "Szécsény",
                            County_name = "Nógrád"
                        },
                        new
                        {
                            Id = 279,
                            City_name = "Szeged",
                            County_name = "Csongrád-Csanád"
                        },
                        new
                        {
                            Id = 280,
                            City_name = "Szeghalom",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 281,
                            City_name = "Székesfehérvár",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 282,
                            City_name = "Szekszárd",
                            County_name = "Tolna"
                        },
                        new
                        {
                            Id = 283,
                            City_name = "Szendrő",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 284,
                            City_name = "Szentendre",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 285,
                            City_name = "Szentes",
                            County_name = "Csongrád-Csanád"
                        },
                        new
                        {
                            Id = 286,
                            City_name = "Szentgotthárd",
                            County_name = "Vas"
                        },
                        new
                        {
                            Id = 287,
                            City_name = "Szentlőrinc",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 288,
                            City_name = "Szerencs",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 289,
                            City_name = "Szigethalom",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 290,
                            City_name = "Szigetszentmiklós",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 291,
                            City_name = "Szigetvár",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 292,
                            City_name = "Szikszó",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 293,
                            City_name = "Szob",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 294,
                            City_name = "Szolnok",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 295,
                            City_name = "Szombathely",
                            County_name = "Vas"
                        },
                        new
                        {
                            Id = 296,
                            City_name = "Tab",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 297,
                            City_name = "Tamási",
                            County_name = "Tolna"
                        },
                        new
                        {
                            Id = 298,
                            City_name = "Tápiószele",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 299,
                            City_name = "Tapolca",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 300,
                            City_name = "Tát",
                            County_name = "Komárom-Esztergom"
                        },
                        new
                        {
                            Id = 301,
                            City_name = "Tata",
                            County_name = "Komárom-Esztergom"
                        },
                        new
                        {
                            Id = 302,
                            City_name = "Tatabánya",
                            County_name = "Komárom-Esztergom"
                        },
                        new
                        {
                            Id = 303,
                            City_name = "Téglás",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 304,
                            City_name = "Tét",
                            County_name = "Győr-Moson-Sopron"
                        },
                        new
                        {
                            Id = 305,
                            City_name = "Tiszacsege",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 306,
                            City_name = "Tiszaföldvár",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 307,
                            City_name = "Tiszafüred",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 308,
                            City_name = "Tiszakécske",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 309,
                            City_name = "Tiszalök",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 310,
                            City_name = "Tiszaújváros",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 311,
                            City_name = "Tiszavasvári",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 312,
                            City_name = "Tokaj",
                            County_name = "Borsod-Abaúj-Zemplén"
                        },
                        new
                        {
                            Id = 313,
                            City_name = "Tolna",
                            County_name = "Tolna"
                        },
                        new
                        {
                            Id = 314,
                            City_name = "Tompa",
                            County_name = "Bács-Kiskun"
                        },
                        new
                        {
                            Id = 315,
                            City_name = "Tótkomlós",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 316,
                            City_name = "Tököl",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 317,
                            City_name = "Törökbálint",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 318,
                            City_name = "Törökszentmiklós",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 319,
                            City_name = "Tura",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 320,
                            City_name = "Túrkeve",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 321,
                            City_name = "Újfehértó",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 322,
                            City_name = "Újhartyán",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 323,
                            City_name = "Újkígyós",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 324,
                            City_name = "Újszász",
                            County_name = "Jász-Nagykun-Szolnok"
                        },
                        new
                        {
                            Id = 325,
                            City_name = "Üllő",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 326,
                            City_name = "Vác",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 327,
                            City_name = "Vaja",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 328,
                            City_name = "Vámospércs",
                            County_name = "Hajdú-Bihar"
                        },
                        new
                        {
                            Id = 329,
                            City_name = "Várpalota",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 330,
                            City_name = "Vásárosnamény",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 331,
                            City_name = "Vasvár",
                            County_name = "Vas"
                        },
                        new
                        {
                            Id = 332,
                            City_name = "Vecsés",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 333,
                            City_name = "Velence",
                            County_name = "Fejér"
                        },
                        new
                        {
                            Id = 334,
                            City_name = "Vép",
                            County_name = "Vas"
                        },
                        new
                        {
                            Id = 335,
                            City_name = "Veresegyház",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 336,
                            City_name = "Verpelét",
                            County_name = "Heves"
                        },
                        new
                        {
                            Id = 337,
                            City_name = "Veszprém",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 338,
                            City_name = "Vésztő",
                            County_name = "Békés"
                        },
                        new
                        {
                            Id = 339,
                            City_name = "Villány",
                            County_name = "Baranya"
                        },
                        new
                        {
                            Id = 340,
                            City_name = "Visegrád",
                            County_name = "Pest"
                        },
                        new
                        {
                            Id = 341,
                            City_name = "Záhony",
                            County_name = "Szabolcs-Szatmár-Bereg"
                        },
                        new
                        {
                            Id = 342,
                            City_name = "Zalaegerszeg",
                            County_name = "Zala"
                        },
                        new
                        {
                            Id = 343,
                            City_name = "Zalakaros",
                            County_name = "Zala"
                        },
                        new
                        {
                            Id = 344,
                            City_name = "Zalalövő",
                            County_name = "Zala"
                        },
                        new
                        {
                            Id = 345,
                            City_name = "Zalaszentgrót",
                            County_name = "Zala"
                        },
                        new
                        {
                            Id = 346,
                            City_name = "Zamárdi",
                            County_name = "Somogy"
                        },
                        new
                        {
                            Id = 347,
                            City_name = "Zirc",
                            County_name = "Veszprém"
                        },
                        new
                        {
                            Id = 348,
                            City_name = "Zsámbék",
                            County_name = "Pest"
                        });
                });

            modelBuilder.Entity("MoveYourBody.Service.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Tag");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Colour = "#6610f2",
                            Name = "Csoportos"
                        },
                        new
                        {
                            Id = 2,
                            Colour = "#05A8AA",
                            Name = "Saját testsúlyos"
                        },
                        new
                        {
                            Id = 3,
                            Colour = "red",
                            Name = "Edzőterem"
                        },
                        new
                        {
                            Id = 4,
                            Colour = "black",
                            Name = "Szabadtéri"
                        },
                        new
                        {
                            Id = 5,
                            Colour = "#0dcaf0",
                            Name = "Zsírégető"
                        },
                        new
                        {
                            Id = 6,
                            Colour = "green",
                            Name = "Személyi edzés"
                        },
                        new
                        {
                            Id = 7,
                            Colour = "#D7263D",
                            Name = "Erőnléti"
                        },
                        new
                        {
                            Id = 8,
                            Colour = "blue",
                            Name = "Aerobic"
                        },
                        new
                        {
                            Id = 9,
                            Colour = "#373F51",
                            Name = "Rehabilitációs"
                        },
                        new
                        {
                            Id = 10,
                            Colour = "#9984D4",
                            Name = "Köredzés"
                        },
                        new
                        {
                            Id = 11,
                            Colour = "#F17300",
                            Name = "Bemelegítés"
                        },
                        new
                        {
                            Id = 12,
                            Colour = "#3A405A",
                            Name = "Flexibilitás"
                        });
                });

            modelBuilder.Entity("MoveYourBody.Service.Models.TagTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Tag_id")
                        .HasColumnType("int");

                    b.Property<int>("Training_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TagTraining");
                });

            modelBuilder.Entity("MoveYourBody.Service.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category_id")
                        .HasColumnType("int");

                    b.Property<string>("Contact_phone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<int>("Max_member")
                        .HasColumnType("int");

                    b.Property<int>("Min_member")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<int>("Trainer_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("MoveYourBody.Service.Models.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address_name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Location_id")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<string>("Place_name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("Training_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TrainingSession");
                });

            modelBuilder.Entity("MoveYourBody.Service.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(320) CHARACTER SET utf8mb4")
                        .HasMaxLength(320);

                    b.Property<string>("Full_name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<int>("Location_id")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasColumnType("varchar(12) CHARACTER SET utf8mb4")
                        .HasMaxLength(12);

                    b.Property<string>("Role")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Trainer")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
