name: MoveYourBody - Docker imagek létrehozása

on: workflow_dispatch

jobs:
  public-backend-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: backend/MoveYourBody/MoveYourBody/MoveYourBody.WebAPI.csproj

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}    
    
    - name: Build the Docker image
      working-directory: backend/MoveYourBody/MoveYourBody
      run: |
        docker build ../ --file Dockerfile -t ghcr.io/adam-mgshgy/moveyourbody:${{steps.get-version.outputs.assembly-version}} -t ghcr.io/adam-mgshgy/moveyourbody:latest 
        docker push ghcr.io/adam-mgshgy/moveyourbody:latest
        docker push ghcr.io/adam-mgshgy/moveyourbody:${{steps.get-version.outputs.assembly-version}}

  publish-client-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: frontend/MoveYourBody 
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}    
    
    - name: Build the Docker image
      working-directory: frontend/MoveYourBody
      run: |
        docker build . --file Dockerfile -t ghcr.io/adam-mgshgy/moveyourbodycli:${{steps.package-version.outputs.current-version}} -t ghcr.io/adam-mgshgy/moveyourbodycli:latest 
        docker push ghcr.io/adam-mgshgy/moveyourbodycli:latest
        docker push ghcr.io/adam-mgshgy/moveyourbodycli:${{steps.package-version.outputs.current-version}}
      